# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-17 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_current_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reports_allowed',
            field=models.CharField(default='daily', max_length=200),
        ),
    ]
