# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180117_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
