# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180130_0953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={},
        ),
    ]
