# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 10:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180130_1003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['priority']},
        ),
    ]
