# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20180130_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='priority',
            field=models.CharField(default='LOW', max_length=4),
        ),
    ]
