# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 19:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20180122_1907'),
        ('api', '0030_merge_20180119_1317'),
    ]

    operations = [
    ]
