# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20180125_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='member_allowed_access',
            field=models.IntegerField(default=0),
        ),
    ]
