# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_merge_20180122_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='department',
        ),
    ]
