# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_check_member_allowed_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='member_allowed_access',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
