# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-26 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20180126_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='member_allowed_email',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
