# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-29 07:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_check_department'),
        ('api', '0031_auto_20180122_1315'),
    ]

    operations = [
    ]
