# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-30 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20180126_0811'),
        ('api', '0035_merge_20180129_0700'),
    ]

    operations = [
    ]
