# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-29 14:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20180126_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='member_allowed_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_requests_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
