# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-30 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_merge_20180130_0822'),
        ('api', '0035_merge_20180129_0859'),
    ]

    operations = [
    ]
