# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20180129_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='is_alerted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='check',
            name='member_allowed_id',
            field=models.IntegerField(default=0),
        ),
    ]
