# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-01 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_merge_20180130_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='is_alerted',
            field=models.BooleanField(default=False),
        ),
    ]
