# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_merge_20180130_1111'),
        ('api', '0038_auto_20180130_1121'),
    ]

    operations = [
    ]
