# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-01 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20180201_0944'),
        ('api', '0031_auto_20180123_2003'),
    ]

    operations = [
    ]
